language: perl

os:
  - linux
# - osx
# No macOS Perl images as of 2020-11-28
# - windows
# Windows does not yet support Perl as of 2020-11-23

perl:
  - "5.32"
  - "5.30"
  - "5.14"
  - "5.8"

# It appears that without travis-perl/helpers only perls 5.14
# through 5.30 work.
before_install:
  - git clone git://github.com/travis-perl/helpers ~/travis-perl-helpers
  - source ~/travis-perl-helpers/init
  - build-perl
  - perl -V
  - build-dist
  - cd $BUILD_DIR       # BUILD_DIR is set by build-dist

install:
  - cpan-install Module::Build # Optional, because you can always use EU::MM
  - cpan-install --deps
